title: Individueel Plan Eimert Vink 2018-2019
description: Becoming a Java developer.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
plugins:
  - jekyll-include-cache
  - jemoji
